### ISSUE TITLE
Repeatedly issuing <ALT>-V will superimpose modals

### ISSUE THREAD

**Issue by quasipedia** [bes89/clipper#1]
When pressing repeatedly <kbd>ALT</kbd><kbd>V</kbd>, the extension will superimpose a new modal displaying the top of the clipboard stack.  Upon selecting the desired entry, the first second dialog will go away, but the first one will stay there indefinitely (until a restart of the shell is performed).
![bug](https://cloud.githubusercontent.com/assets/309045/17142064/efc102a4-534e-11e6-8a0d-b2ff73d9269b.gif)

**Comment by bes89** [comment]
thank you! :+1:
